import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';
import { jsPDF } from 'npm:jspdf@4.0.0';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await req.json();
    const { incidentId } = body;

    if (!incidentId) {
      return Response.json({ error: 'Incident ID is required' }, { status: 400 });
    }

    // Fetch incident details
    const incidents = await base44.entities.Incident.filter({ id: incidentId });
    if (incidents.length === 0) {
      return Response.json({ error: 'Incident not found' }, { status: 404 });
    }

    const incident = incidents[0];

    // Fetch related tasks
    const allTasks = await base44.entities.IncidentTask.filter({ incident_id: incidentId });

    // Fetch communications
    const allComms = await base44.entities.Communication.list();

    // Fetch evidence
    const allEvidence = await base44.entities.Evidence.list();

    // Create PDF
    const doc = new jsPDF();
    let yPosition = 20;
    const pageHeight = doc.internal.pageSize.height;
    const pageWidth = doc.internal.pageSize.width;
    const margin = 15;
    const lineHeight = 5;
    const maxWidth = pageWidth - 2 * margin;

    const addHeading = (text, fontSize = 16, color = [0, 0, 0]) => {
      if (yPosition + 10 > pageHeight - 10) {
        doc.addPage();
        yPosition = 20;
      }
      doc.setFontSize(fontSize);
      doc.setTextColor(...color);
      doc.text(text, margin, yPosition);
      yPosition += lineHeight * 2.5;
    };

    const addSubHeading = (text) => {
      if (yPosition + 8 > pageHeight - 10) {
        doc.addPage();
        yPosition = 20;
      }
      doc.setFontSize(12);
      doc.setTextColor(0, 0, 0);
      doc.setFont(undefined, 'bold');
      doc.text(text, margin, yPosition);
      yPosition += lineHeight * 2;
      doc.setFont(undefined, 'normal');
    };

    const addText = (label, value, fontSize = 10) => {
      if (yPosition + 6 > pageHeight - 10) {
        doc.addPage();
        yPosition = 20;
      }
      doc.setFontSize(fontSize);
      doc.setFont(undefined, 'bold');
      doc.text(label + ':', margin, yPosition);
      doc.setFont(undefined, 'normal');
      const lines = doc.splitTextToSize(String(value || ''), maxWidth - 50);
      doc.text(lines, margin + 50, yPosition);
      yPosition += lineHeight * Math.max(1.5, lines.length * 1.2);
    };

    const addLine = () => {
      if (yPosition + 3 > pageHeight - 10) {
        doc.addPage();
        yPosition = 20;
      }
      doc.setDrawColor(200, 200, 200);
      doc.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += lineHeight;
    };

    // Title Page
    doc.setFontSize(24);
    doc.setTextColor(139, 0, 0);
    doc.setFont(undefined, 'bold');
    doc.text('RICS CONDUCT INVESTIGATION', margin, yPosition);
    yPosition += lineHeight * 2;
    doc.text('Incident Report', margin, yPosition);
    yPosition += lineHeight * 3;

    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.setFont(undefined, 'normal');
    doc.text(`Generated: ${new Date().toLocaleDateString('en-GB', { year: 'numeric', month: 'long', day: 'numeric' })}`, margin, yPosition);
    yPosition += lineHeight * 2;
    doc.text(`Generated by: ${user.full_name || user.email}`, margin, yPosition);
    yPosition += lineHeight * 4;

    addLine();
    yPosition += lineHeight;

    // Executive Summary
    addHeading('EXECUTIVE SUMMARY', 16, [139, 0, 0]);

    addText('Incident Title', incident.data.title);
    addText('Incident Type', incident.data.incident_type);
    addText('Date of Incident', new Date(incident.data.date).toLocaleDateString('en-GB'));
    addText('Severity Level', incident.data.severity.toUpperCase());
    addText('Current Status', incident.data.status);

    if (incident.data.rics_violations && incident.data.rics_violations.length > 0) {
      addText('RICS Violations Identified', incident.data.rics_violations.join(', '));
    }

    if (incident.data.legal_issues && incident.data.legal_issues.length > 0) {
      addText('Potential Legal Issues', incident.data.legal_issues.join(', '));
    }

    yPosition += lineHeight;
    addLine();

    // Incident Details
    addHeading('INCIDENT DETAILS', 14, [139, 0, 0]);

    if (incident.data.description) {
      doc.setFontSize(10);
      doc.setFont(undefined, 'bold');
      doc.text('Description:', margin, yPosition);
      yPosition += lineHeight * 1.5;
      doc.setFont(undefined, 'normal');
      const descLines = doc.splitTextToSize(incident.data.description, maxWidth);
      doc.text(descLines, margin, yPosition);
      yPosition += lineHeight * Math.max(1, descLines.length * 1.2) + lineHeight;
    }

    if (incident.data.evidence_notes) {
      addText('Evidence Notes', incident.data.evidence_notes);
    }

    if (incident.data.witnesses && incident.data.witnesses.length > 0) {
      addText('Witnesses', incident.data.witnesses.join(', '));
    }

    yPosition += lineHeight;
    addLine();

    // Tasks
    if (allTasks.length > 0) {
      addHeading('INCIDENT TASKS', 14, [139, 0, 0]);

      allTasks.forEach((task, idx) => {
        if (yPosition + 15 > pageHeight - 10) {
          doc.addPage();
          yPosition = 20;
        }

        doc.setFontSize(10);
        doc.setFont(undefined, 'bold');
        doc.text(`Task ${idx + 1}: ${task.data.title}`, margin, yPosition);
        yPosition += lineHeight * 1.5;

        doc.setFont(undefined, 'normal');
        addText('Status', task.data.status);
        addText('Priority', task.data.priority);
        addText('Assigned To', task.data.assigned_to || 'Unassigned');

        if (task.data.deadline) {
          addText('Deadline', new Date(task.data.deadline).toLocaleDateString('en-GB'));
        }

        if (task.data.notes) {
          addText('Notes', task.data.notes);
        }

        yPosition += lineHeight;
        doc.setDrawColor(220, 220, 220);
        doc.line(margin, yPosition, pageWidth - margin, yPosition);
        yPosition += lineHeight * 1.5;
      });

      addLine();
    }

    // Communications
    const relatedComms = allComms.filter(c => 
      incident.data.title && c.data.subject?.includes(incident.data.title.substring(0, 20))
    );

    if (relatedComms.length > 0) {
      addHeading('COMMUNICATIONS', 14, [139, 0, 0]);

      relatedComms.forEach((comm, idx) => {
        if (yPosition + 15 > pageHeight - 10) {
          doc.addPage();
          yPosition = 20;
        }

        doc.setFontSize(10);
        doc.setFont(undefined, 'bold');
        doc.text(`Communication ${idx + 1}`, margin, yPosition);
        yPosition += lineHeight * 1.5;

        doc.setFont(undefined, 'normal');
        addText('Date', new Date(comm.data.date).toLocaleDateString('en-GB'));
        addText('Type', comm.data.type);
        addText('From', comm.data.from);
        addText('To', comm.data.to);
        addText('Subject', comm.data.subject);

        if (comm.data.tone) {
          addText('Tone Assessment', comm.data.tone);
        }

        if (comm.data.content) {
          doc.setFont(undefined, 'bold');
          doc.text('Content:', margin, yPosition);
          yPosition += lineHeight * 1.5;
          doc.setFont(undefined, 'normal');
          const contentLines = doc.splitTextToSize(comm.data.content.substring(0, 300), maxWidth);
          doc.text(contentLines, margin, yPosition);
          yPosition += lineHeight * Math.max(1, contentLines.length * 1.2);
        }

        yPosition += lineHeight;
        doc.setDrawColor(220, 220, 220);
        doc.line(margin, yPosition, pageWidth - margin, yPosition);
        yPosition += lineHeight * 1.5;
      });

      addLine();
    }

    // Evidence Summary
    const relatedEvidence = allEvidence.filter(e =>
      e.data.related_incidents?.includes(incidentId)
    );

    if (relatedEvidence.length > 0) {
      addHeading('SUPPORTING EVIDENCE', 14, [139, 0, 0]);

      relatedEvidence.forEach((ev, idx) => {
        if (yPosition + 12 > pageHeight - 10) {
          doc.addPage();
          yPosition = 20;
        }

        doc.setFontSize(10);
        doc.setFont(undefined, 'bold');
        doc.text(`${idx + 1}. ${ev.data.title}`, margin, yPosition);
        yPosition += lineHeight * 1.5;

        doc.setFont(undefined, 'normal');
        addText('Type', ev.data.evidence_type);
        addText('Date Collected', new Date(ev.data.date_collected).toLocaleDateString('en-GB'));
        addText('Relevance', ev.data.relevance);
        addText('Strength', ev.data.strength);

        if (ev.data.description) {
          addText('Description', ev.data.description);
        }

        yPosition += lineHeight;
      });

      addLine();
    }

    // Footer
    yPosition = pageHeight - 15;
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 120);
    doc.text(`Page ${doc.getPageCount()}`, pageWidth / 2, yPosition, { align: 'center' });

    // Generate PDF
    const pdfBytes = doc.output('arraybuffer');

    return new Response(pdfBytes, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="Incident_Report_${incidentId}_${new Date().toISOString().split('T')[0]}.pdf"`
      }
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});