import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';
import { jsPDF } from 'npm:jspdf@4.0.0';

Deno.serve(async (req) => {
    try {
        const base44 = createClientFromRequest(req);
        const user = await base44.auth.me();
        
        if (!user) {
            return Response.json({ error: 'Unauthorized' }, { status: 401 });
        }

        const { report_type, case_id } = await req.json();

        if (!report_type) {
            return Response.json({ error: 'Report type required' }, { status: 400 });
        }

        // Fetch relevant data based on report type
        let reportData = {};
        
        if (report_type === 'rics_breach') {
            const incidents = await base44.entities.Incident.filter({});
            const ricsRules = await base44.entities.RICSRule.filter({});
            
            const breachIncidents = incidents.filter(i => i.rics_violations?.length > 0);
            
            reportData = {
                title: 'RICS Breach Notification Report',
                subtitle: 'Professional Conduct Violation Summary',
                generated_date: new Date().toLocaleDateString('en-GB'),
                total_incidents: breachIncidents.length,
                violations: breachIncidents.map(incident => ({
                    date: incident.date,
                    title: incident.title,
                    description: incident.description,
                    severity: incident.severity,
                    violations: incident.rics_violations,
                    legal_issues: incident.legal_issues
                })),
                rules_reference: ricsRules.slice(0, 10)
            };
        } else if (report_type === 'gift_aid') {
            // Placeholder for charity data - would need Charity entity
            reportData = {
                title: 'Gift Aid Declaration Summary',
                subtitle: 'Charity Commission Compliance Report',
                generated_date: new Date().toLocaleDateString('en-GB'),
                note: 'Gift aid data requires Charity entity integration'
            };
        } else if (report_type === 'gas_safety') {
            // Placeholder for property compliance data
            reportData = {
                title: 'Gas Safety Compliance Report',
                subtitle: 'Property Safety Certificate Summary',
                generated_date: new Date().toLocaleDateString('en-GB'),
                note: 'Gas safety data requires Property entity integration'
            };
        } else if (report_type === 'limitation_dates') {
            const cases = await base44.entities.LegalCase.filter({});
            const alerts = await base44.entities.ComplianceAlert.filter({});
            
            const urgentCases = cases.filter(c => {
                if (!c.limitation_date) return false;
                const daysUntil = Math.ceil((new Date(c.limitation_date) - new Date()) / (1000 * 60 * 60 * 24));
                return daysUntil <= 30;
            });
            
            reportData = {
                title: 'Limitation Date Compliance Report',
                subtitle: 'Critical Deadline Tracking Summary',
                generated_date: new Date().toLocaleDateString('en-GB'),
                total_cases: cases.length,
                urgent_cases: urgentCases.length,
                cases: urgentCases.map(c => ({
                    case_ref: c.case_ref,
                    client_name: c.client_name,
                    limitation_date: c.limitation_date,
                    days_remaining: Math.ceil((new Date(c.limitation_date) - new Date()) / (1000 * 60 * 60 * 24)),
                    status: c.status
                })),
                active_alerts: alerts.filter(a => a.status === 'active').length
            };
        }

        // Generate PDF
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();
        
        // Header with branding
        doc.setFillColor(30, 58, 138); // Blue-800
        doc.rect(0, 0, pageWidth, 40, 'F');
        
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(24);
        doc.setFont('helvetica', 'bold');
        doc.text(reportData.title, 15, 20);
        
        doc.setFontSize(12);
        doc.setFont('helvetica', 'normal');
        doc.text(reportData.subtitle || '', 15, 30);
        
        // Metadata
        doc.setTextColor(100, 100, 100);
        doc.setFontSize(10);
        doc.text(`Generated: ${reportData.generated_date}`, 15, 48);
        doc.text(`Generated by: ${user.full_name || user.email}`, 15, 53);
        
        // Content
        let yPos = 65;
        doc.setTextColor(0, 0, 0);
        
        if (report_type === 'rics_breach') {
            doc.setFontSize(14);
            doc.setFont('helvetica', 'bold');
            doc.text(`Total Breach Incidents: ${reportData.total_incidents}`, 15, yPos);
            yPos += 15;
            
            reportData.violations.forEach((violation, idx) => {
                if (yPos > 270) {
                    doc.addPage();
                    yPos = 20;
                }
                
                doc.setFontSize(12);
                doc.setFont('helvetica', 'bold');
                doc.text(`${idx + 1}. ${violation.title}`, 15, yPos);
                yPos += 8;
                
                doc.setFontSize(10);
                doc.setFont('helvetica', 'normal');
                doc.text(`Date: ${violation.date} | Severity: ${violation.severity}`, 15, yPos);
                yPos += 6;
                
                const splitDesc = doc.splitTextToSize(violation.description, 180);
                doc.text(splitDesc, 15, yPos);
                yPos += (splitDesc.length * 5) + 2;
                
                if (violation.violations?.length > 0) {
                    doc.setFont('helvetica', 'bold');
                    doc.text('RICS Violations:', 15, yPos);
                    yPos += 6;
                    doc.setFont('helvetica', 'normal');
                    violation.violations.forEach(rule => {
                        doc.text(`• ${rule}`, 20, yPos);
                        yPos += 5;
                    });
                    yPos += 2;
                }
                
                yPos += 5;
            });
        } else if (report_type === 'limitation_dates') {
            doc.setFontSize(14);
            doc.setFont('helvetica', 'bold');
            doc.text(`Total Cases: ${reportData.total_cases} | Urgent Cases: ${reportData.urgent_cases}`, 15, yPos);
            yPos += 15;
            
            reportData.cases.forEach((c, idx) => {
                if (yPos > 270) {
                    doc.addPage();
                    yPos = 20;
                }
                
                const daysColor = c.days_remaining < 0 ? [220, 38, 38] : c.days_remaining <= 7 ? [234, 179, 8] : [34, 197, 94];
                doc.setFillColor(...daysColor);
                doc.rect(15, yPos - 8, 180, 25, 'F');
                
                doc.setTextColor(255, 255, 255);
                doc.setFontSize(11);
                doc.setFont('helvetica', 'bold');
                doc.text(`${c.case_ref} - ${c.client_name}`, 20, yPos);
                yPos += 6;
                
                doc.setFont('helvetica', 'normal');
                doc.text(`Limitation Date: ${c.limitation_date} | Days Remaining: ${c.days_remaining}`, 20, yPos);
                yPos += 6;
                doc.text(`Status: ${c.status}`, 20, yPos);
                yPos += 12;
                
                doc.setTextColor(0, 0, 0);
            });
        } else {
            doc.setFontSize(12);
            doc.text(reportData.note || 'No data available', 15, yPos);
        }
        
        // Footer
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150, 150, 150);
            doc.text(`Page ${i} of ${pageCount}`, pageWidth - 30, doc.internal.pageSize.getHeight() - 10);
        }
        
        const pdfBytes = doc.output('arraybuffer');
        
        return new Response(pdfBytes, {
            status: 200,
            headers: {
                'Content-Type': 'application/pdf',
                'Content-Disposition': `attachment; filename="${report_type.replace('_', '-')}-report-${new Date().toISOString().split('T')[0]}.pdf"`
            }
        });
    } catch (error) {
        console.error('Error generating compliance report:', error);
        return Response.json({ error: error.message }, { status: 500 });
    }
});